### ISSUE TITLE
File svm.falsePositiveThreshold doesn't exist

### ISSUE THREAD

**Issue by yuriyward** [duongch4/objectDetection#1]
Hi,
thank you for sharing your solution for Car Detection,
I have problem with testing due to lack of file svm.falsePositiveThreshold.
It is not created automatically during training and is not included in the repository, could you add it?

**Comment by duongch4** [comment]
Hi,
Thank you for pointing that out.
I just updated the files, and svm.falsePositiveThreshold should be generated automatically now.
Let me know if there is any more issue

**Comment by yuriyward** [comment]
Now works well, thank you :)
